### ISSUE TITLE
v2 still in beta?

### ISSUE THREAD

**Issue by VincentMarmiesse** [UniAlteri/sellsy-client#9]
Hi,

Thanks for your work!

Is the v2 still in beta?

Composer doesn't want to require it because I have a minimum stability of stable.

**Comment by frenchcomp** [comment]
Hi,
I have no support from Sellsy, (no test account, no feedback), only feedback from user.
But there are no new issue on Github since december, I will release a the stable this week end :).
While waiting this, you can add in your composer.json the line "teknoo/sellsy-client: 2.0.0-beta2" to bypass the minimum-stability requirement for this package :)

Have a nice day
Richard

**Comment by frenchcomp** [comment]
The version 2.0 has been released.
Have a nice day :)
Richard
